apple = "I like to eat apples."
igloo = "An igloo is a house made of snow. Isn't that cool?"
otter = "I love otters. They like to play all day, like me!"
queen = "A queen is a girl ruler. England has had several queens."
under = "There lots of bugs under the ground. Gross!"
watch = "Birds are fun to watch. Sometimes they argue with their little bird voices."
zebra = "Zebras look like striped horses."
