bat = "I swing my bat when I play baseball."
car = "I like to watch cars race. Do you?"
cat = "Cats have big triangle ears and whiskers."
dog = "Dogs go woof woof!"
eat = "I don't like vegetables, but I eat them anyway."
fan = "Fans keep me cool in the summer."
fat = "Fat is used by my body to store energy."
gum = "Did you know you can blow bubbles with gum?"
hat = "Farmers wear straw hats to keep the sun out of their eyes."
kid = "Most kids like to play in the park. Do you?"
mat = "When people do yoga, they often use a mat."
mom = "Mom gives me a big hug when I come home from school."
net = "People use nets to catch fish. Do you like fish?"
pat = "I like to pat cute furry animals."
rat = "A rat is like a big mouse. They can be trained to do tricks!"
sat = "I sat in a desk at school, and paid attention to my teacher."
top = "My mother cuts food on top of a cutting board."
you = "You are very special!"
