jump = "Sometimes, when I'm excited, I jump up and down!"
lion = "Boy lions have a big mane."
pear = "Pears are very sweet."
very = "I am very happy to be learning how to spell words with you!"
xray = "X-rays are used to look at people's bones."
