apple = "I like to eat apples."
bat = "I swing my bat when I play baseball."
car = "I like to watch cars race. Do you?"
dog = "Dogs go woof woof!"
eat = "I don't like vegetables, but I eat them anyway."
fan = "Fans keep me cool in the summer."
gum = "Did you know you can blow bubbles with gum?"
hat = "Farmers wear straw hats to keep the sun out of their eyes."
igloo = "An igloo is a house made of snow. Isn't that cool?"
jump = "Sometimes, when I'm excited, I jump up and down!"
kid = "Most kids like to play in the park. Do you?"
lion = "Boy lions have a big mane."
mom = "Mom gives me a big hug when I come home from school."
net = "People use nets to catch fish. Do you like fish?"
otter = "I love otters. They like to play all day, like me!"
pear = "Pears are very sweet."
queen = "A queen is a girl ruler. England has had several queens."
rat = "A rat is like a big mouse. They can be trained to do tricks!"
top = "My mother cuts food on top of a cutting board."
under = "There a lots of bugs under the ground. Gross!"
very = "I am very happy to be learning how to spell words with you!"
watch = "Birds are fun to watch. Sometimes they argue with their little bird voices."
xray = "X-rays are used to look at people's bones."
you = "You are very special!"
zebra = "Zebras look like striped horses."
